/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package info.perezalcolea.dependency.management;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }
}
